name: Hyd Jobs Bot
on:
  schedule:
    - cron: '0 */3 * * *' # 3 hours ki okasari - block avvadhu
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          YOUR_GMAIL: ${{ secrets.YOUR_GMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
        run: |
          pip install requests beautifulsoup4 lxml
          python main.py
      - name: Save
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@hyd.com"
          git add posted.json || true
          git commit -m "hyd jobs" || true
          git push || true
